version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12

    environment:
      TEST_RESULTS: /tmp/test-results
      CC_TEST_REPORTER_ID: d4297759a5452ea7e6df5ef07da70ed284449f7cdf026497e0d302513bc78284

    working_directory: /go/src/github.com/kylegrantlucas/platform-exercise
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: CodeClimate Before Build
          command: |
            ./cc-test-reporter before-build
      - run:
          name: Run tests
          environment:
            JWT_KEY: fenderdigital

          command: |
            set -o pipefail
            mkdir -p /tmp/test-results/platform
            touch /tmp/test-results/platform/report.xml
            go test -coverprofile=c.out -tags=integration -v ./... | tee >(go-junit-report > /tmp/test-results/platform/report.xml)
      - run:
          name: CodeClimate After Build
          command: |
            ./cc-test-reporter after-build || true
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results